//! `NetworkPolicy` -> Cedar policy set.

use std::fmt::Write as _;

use anyhow::{Context as _, Result, bail};
use cedar_policy::{PolicySet, ValidationMode, Validator};
use k8s_openapi::api::networking::v1::NetworkPolicy;

use crate::expr::{Expr, entity_uid};
use crate::peer::peer_expr;
use crate::port::port_expr;
use crate::schema;
use crate::selector::selector_expr;

/// One half of the Kubernetes connection decision.
///
/// Kubernetes requires *both* the source's egress rules and the destination's
/// ingress rules to allow a connection. Cedar's `permit` is a disjunction, so the
/// conjunction cannot live inside one request: each direction is its own action and
/// the caller ANDs the two decisions.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Direction {
    Ingress,
    Egress,
}

impl Direction {
    pub const ALL: [Direction; 2] = [Direction::Ingress, Direction::Egress];

    /// The Cedar action name, and the `policyTypes` entry that enables it.
    pub fn action(self) -> &'static str {
        match self {
            Direction::Ingress => "ingress",
            Direction::Egress => "egress",
        }
    }

    fn policy_type(self) -> &'static str {
        match self {
            Direction::Ingress => "Ingress",
            Direction::Egress => "Egress",
        }
    }

    /// The variable standing for the pod that `spec.podSelector` binds. Always a Pod.
    fn selected(self) -> &'static str {
        match self {
            Direction::Ingress => "resource",
            Direction::Egress => "principal",
        }
    }

    /// The variable standing for the peer named in `from`/`to`. May not be a Pod.
    fn peer(self) -> &'static str {
        match self {
            Direction::Ingress => "principal",
            Direction::Egress => "resource",
        }
    }
}

impl std::fmt::Display for Direction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.action())
    }
}

/// The compiler's output: the `.cedar` text (a deliverable in its own right) and the
/// parsed, strictly-validated policy set built from it.
pub struct Compiled {
    pub source: String,
    pub policy_set: PolicySet,
}

/// Compile a set of NetworkPolicy objects into a Cedar policy set.
///
/// Input order does not matter: policies are sorted by `namespace/name` so that the
/// generated text depends only on the objects themselves.
pub fn compile(policies: &[NetworkPolicy]) -> Result<Compiled> {
    let mut sorted: Vec<(String, String, &NetworkPolicy)> = policies
        .iter()
        .map(|np| {
            let (ns, name) = object_ref(np)?;
            Ok((ns, name, np))
        })
        .collect::<Result<_>>()?;
    sorted.sort_by(|a, b| (&a.0, &a.1).cmp(&(&b.0, &b.1)));

    let mut source = String::new();
    let _ = write!(
        source,
        "\
// Generated by np2cedar from {} NetworkPolicy object(s). Do not edit by hand.
//
// A connection source -> destination is allowed if and only if BOTH decisions
// are Allow, because Kubernetes requires the sending and receiving ends to agree:
//
//   is_authorized(Action::\"egress\",  source, destination, context)
//   is_authorized(Action::\"ingress\", source, destination, context)
",
        sorted.len()
    );

    for direction in Direction::ALL {
        source.push('\n');
        source.push_str(&catch_all(&sorted, direction)?);
    }

    for (ns, name, np) in &sorted {
        for direction in Direction::ALL {
            if !applies_to(np, direction) {
                continue;
            }
            for (index, rule) in rules(np, direction).iter().enumerate() {
                source.push('\n');
                source.push_str(&rule_policy(ns, name, np, direction, index, rule)?);
            }
        }
    }

    let policy_set: PolicySet = source.parse().with_context(|| {
        format!("generated Cedar did not parse (this is a compiler bug):\n{source}")
    })?;

    let result = Validator::new(schema().clone()).validate(&policy_set, ValidationMode::Strict);
    if !result.validation_passed() {
        let errors = result
            .validation_errors()
            .map(|e| format!("  - {e}"))
            .collect::<Vec<_>>()
            .join("\n");
        bail!("generated Cedar failed strict validation (this is a compiler bug):\n{errors}");
    }

    Ok(Compiled { source, policy_set })
}

/// `namespace/name` of a NetworkPolicy, which is also its `@k8sPolicy` annotation.
fn object_ref(np: &NetworkPolicy) -> Result<(String, String)> {
    let name = np
        .metadata
        .name
        .clone()
        .context("NetworkPolicy is missing metadata.name")?;
    let namespace = np
        .metadata
        .namespace
        .clone()
        .with_context(|| format!("NetworkPolicy {name} is missing metadata.namespace"))?;
    Ok((namespace, name))
}

/// `policyTypes` defaulting, per the Kubernetes API contract: when the field is
/// unset, Ingress always applies and Egress applies exactly when an `egress`
/// section is present — even an empty one.
fn applies_to(np: &NetworkPolicy, direction: Direction) -> bool {
    let Some(spec) = &np.spec else { return false };
    match &spec.policy_types {
        Some(types) => types.iter().any(|t| t == direction.policy_type()),
        None => match direction {
            Direction::Ingress => true,
            Direction::Egress => spec.egress.is_some(),
        },
    }
}

/// One rule of `spec.ingress` / `spec.egress`, normalised across the two directions.
struct Rule<'a> {
    peers: &'a [k8s_openapi::api::networking::v1::NetworkPolicyPeer],
    ports: &'a [k8s_openapi::api::networking::v1::NetworkPolicyPort],
    /// `"from"` or `"to"`, for the generated comment.
    peer_field: &'static str,
}

fn rules(np: &NetworkPolicy, direction: Direction) -> Vec<Rule<'_>> {
    let Some(spec) = &np.spec else {
        return Vec::new();
    };
    match direction {
        Direction::Ingress => spec
            .ingress
            .iter()
            .flatten()
            .map(|r| Rule {
                peers: r.from.as_deref().unwrap_or_default(),
                ports: r.ports.as_deref().unwrap_or_default(),
                peer_field: "from",
            })
            .collect(),
        Direction::Egress => spec
            .egress
            .iter()
            .flatten()
            .map(|r| Rule {
                peers: r.to.as_deref().unwrap_or_default(),
                ports: r.ports.as_deref().unwrap_or_default(),
                peer_field: "to",
            })
            .collect(),
    }
}

/// The condition selecting the pods a policy isolates: its namespace plus its
/// `spec.podSelector`, over the variable that stands for the selected pod.
fn isolation_expr(ns: &str, np: &NetworkPolicy, direction: Direction) -> Result<Expr> {
    let selected = direction.selected();
    let pod_selector = np.spec.as_ref().and_then(|s| s.pod_selector.as_ref());
    Ok(Expr::and([
        Expr::atom(format!(
            "{selected}.namespace == {}",
            entity_uid("Namespace", ns)
        )),
        selector_expr(pod_selector, &format!("{selected}.labels"))?,
    ]))
}

/// The default-allow half of the Kubernetes rule: a pod becomes *isolated* for a
/// direction the moment any policy of that type selects it, and thereafter only
/// explicitly-permitted traffic gets through. Everything else is allowed.
///
/// `X is Pod &&` means a non-Pod endpoint is never isolated, which is correct —
/// NetworkPolicy governs pods only.
fn catch_all(
    policies: &[(String, String, &NetworkPolicy)],
    direction: Direction,
) -> Result<String> {
    let action = direction.action();
    let selected = direction.selected();

    let isolated: Vec<Expr> = policies
        .iter()
        .filter(|(_, _, np)| applies_to(np, direction))
        .map(|(ns, name, np)| {
            Ok(isolation_expr(ns, np, direction)?.commented(format!("{ns}/{name}")))
        })
        .collect::<Result<_>>()?;

    let mut out = format!(
        "\
// Pods selected by no {}-type NetworkPolicy are not isolated for {action}.
@k8sKind(\"catch-all\")
@k8sDirection(\"{action}\")
permit (principal, action == Action::\"{action}\", resource)",
        direction.policy_type()
    );

    let isolated = Expr::or(isolated);
    if isolated.is_const() {
        // No policy of this type exists anywhere: nothing is isolated.
        out.push_str(";\n");
    } else {
        let guard = Expr::and([Expr::atom(format!("{selected} is Pod")), isolated]);
        let _ = write!(out, "\nunless {{\n  {}\n}};\n", guard.render(2));
    }
    Ok(out)
}

/// Combine the alternatives of a `from`/`to`/`ports` list.
///
/// An *empty* list means "unrestricted" in Kubernetes, so the clause drops out of
/// the enclosing conjunction. That is `true`, emphatically not the `false` an empty
/// disjunction would give.
fn any_of(alternatives: Vec<Expr>) -> Expr {
    if alternatives.is_empty() {
        Expr::Bool(true)
    } else {
        Expr::or(alternatives)
    }
}

/// One `permit` per NetworkPolicy rule. Additivity across policies is free: two
/// policies selecting the same pod produce two permits, which Cedar ORs.
fn rule_policy(
    ns: &str,
    name: &str,
    np: &NetworkPolicy,
    direction: Direction,
    index: usize,
    rule: &Rule<'_>,
) -> Result<String> {
    let action = direction.action();
    let selected = direction.selected();
    let peer_var = direction.peer();

    let mut parts = vec![
        isolation_expr(ns, np, direction)?
            .commented(format!("spec.podSelector, in the policy's namespace {ns}")),
    ];

    let peers = rule
        .peers
        .iter()
        .map(|p| peer_expr(p, peer_var, ns))
        .collect::<Result<Vec<_>>>()
        .with_context(|| format!("{ns}/{name}: {action}[{index}].{}", rule.peer_field))?;
    parts.push(any_of(peers).commented(format!("{action}[{index}].{} (any of)", rule.peer_field)));

    let ports = rule
        .ports
        .iter()
        .map(port_expr)
        .collect::<Result<Vec<_>>>()
        .with_context(|| format!("{ns}/{name}: {action}[{index}].ports"))?;
    parts.push(any_of(ports).commented(format!("{action}[{index}].ports (any of)")));

    let condition = Expr::and(parts);

    let mut out = format!(
        "\
@k8sPolicy(\"{ns}/{name}\")
@k8sDirection(\"{action}\")
@k8sRule(\"{index}\")
permit (
  {},
  action == Action::\"{action}\",
  {}
)",
        if selected == "principal" {
            "principal is Pod"
        } else {
            "principal"
        },
        if selected == "resource" {
            "resource is Pod"
        } else {
            "resource"
        },
    );
    match condition {
        // `permit(...)` with no `when` is the same policy, minus the noise.
        Expr::Bool(true) => out.push_str(";\n"),
        other => {
            let _ = write!(out, "\nwhen {{\n  {}\n}};\n", other.render(2));
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use k8s_openapi::api::networking::v1::{NetworkPolicyIngressRule, NetworkPolicySpec};
    use k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta;

    fn policy(spec: NetworkPolicySpec) -> NetworkPolicy {
        NetworkPolicy {
            metadata: ObjectMeta {
                name: Some("p".into()),
                namespace: Some("default".into()),
                ..Default::default()
            },
            spec: Some(spec),
        }
    }

    #[test]
    fn policy_types_default_from_the_sections_present() {
        let no_egress = policy(NetworkPolicySpec::default());
        assert!(applies_to(&no_egress, Direction::Ingress));
        assert!(!applies_to(&no_egress, Direction::Egress));

        // An `egress` section — even an empty one — turns Egress on, and Ingress
        // stays on regardless.
        let with_egress = policy(NetworkPolicySpec {
            egress: Some(vec![]),
            ..Default::default()
        });
        assert!(applies_to(&with_egress, Direction::Ingress));
        assert!(applies_to(&with_egress, Direction::Egress));

        // An explicit `policyTypes` overrides the defaulting entirely.
        let explicit = policy(NetworkPolicySpec {
            egress: Some(vec![]),
            policy_types: Some(vec!["Egress".into()]),
            ..Default::default()
        });
        assert!(!applies_to(&explicit, Direction::Ingress));
        assert!(applies_to(&explicit, Direction::Egress));
    }

    #[test]
    fn an_empty_from_or_ports_list_means_unrestricted() {
        // Regression: an empty alternatives list is the identity of the enclosing
        // conjunction, not an empty disjunction, which would be `false` and would
        // silently deny everything the rule was meant to allow.
        assert_eq!(any_of(vec![]), Expr::Bool(true));
        assert_eq!(any_of(vec![Expr::Bool(false)]), Expr::Bool(false));

        let rule = policy(NetworkPolicySpec {
            policy_types: Some(vec!["Ingress".into()]),
            ingress: Some(vec![NetworkPolicyIngressRule::default()]),
            ..Default::default()
        });
        let compiled = compile(&[rule]).unwrap();
        assert!(
            !compiled.source.contains("when {\n  false\n}"),
            "a rule with no `from` and no `ports` must allow everything:\n{}",
            compiled.source
        );
    }

    #[test]
    fn a_policy_missing_its_namespace_is_rejected() {
        let orphan = NetworkPolicy {
            metadata: ObjectMeta {
                name: Some("p".into()),
                ..Default::default()
            },
            spec: Some(NetworkPolicySpec::default()),
        };
        assert!(compile(&[orphan]).is_err());
    }

    #[test]
    fn no_policies_at_all_leaves_everything_permitted() {
        let compiled = compile(&[]).unwrap();
        assert!(
            compiled
                .source
                .contains("permit (principal, action == Action::\"ingress\", resource);")
        );
        assert!(
            compiled
                .source
                .contains("permit (principal, action == Action::\"egress\", resource);")
        );
    }
}
